export const environment = {
  production: true,
  SpotifyApiKey: 'BQB2Da37fUlxXrZ5hvvzt0Qc5cWAMJmjqTJXcDpri0ST7B8HcJuzryBOe18dI1GdBkylu3UcZMLsxqFQd0lARhtec0krNb5YoaEJOTPTmlXUZEi3R_iQJBVAHAWCJuIVOmuDzxjpqBmKbng0RVqU4MFqKopIvkFRiHfsrXqlc6bk9c80pEAxX3OfXpnPBJRBWJAjIArVOv7UzOmGh_QhyHKwA0TqaeAWQY1-wVkD2bkZvGoO9hSlttD5RPpMuXdpfVS8jtZNKUQdp-igLMF5eftmUPs'
};
